openapi: 3.0.3
x-json-schema-faker:
  maxItems: 3
info:
  title: Capitura - Project
  description: |
    API Backend para applicação Capitura - Project.
  termsOfService: juliocesarmcamilo@gmail.com
  contact:
    name: Júlio C. Mesquita
    url: juliocesarmcamilo@gmail.com
    email: juliocesarmcamilo@gmail.com
  license:
    name: Capitura - Project - Licença comercial
    url: juliocesarmcamilo@gmail.com
  version: 0.0.01
externalDocs:
  description: Capitura - Project - Documentação
  url: juliocesarmcamilo@gmail.com
servers:
  - url: "{protocol}://{devServerHost}:{devServerPort}/api/seict-comprac/v1"
    description: development instance
    variables:
      protocol:
        description: host name of the protocol
        default: http
        enum:
          - http
      devServerHost:
        description: host name of the development server
        default: localhost
        enum:
          - localhost
          # add other hosts here
      devServerPort:
        description: host port of the api service is running
        default: "8080"
        enum:
          - "8081"
          - "8080"
          # add other ports here
tags:
  - name: Back Office - Capitura
    description: Management of Job Opportunities
  - name: User Profile - Capitura
    description: Managing your profile for job opportunities.

components:
  schemas:
#    Criando um objeto do tipo problema
    Problem:
      description: todo
      type: object
      properties:
        type:
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          type: string
          format: uri
          minLength: 10
          maxLength: 2147483647
          default: "about:blank"
          example: "https://capitur/problem/constraint-violation"
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
          minLength: 1
          maxLength: 2147483647
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          type: integer
          format: int32
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          type: string
          minLength: 1
          maxLength: 2147483647
          example: Connection to database timed out
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          type: string
          format: uri
          minLength: 1
          maxLength: 2147483647

#    Criando um UUID
    IdAsUUID:
      description: type of id used in the system.
      type: string
      pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      minLength: 36
      maxLength: 36

#    Criando os tipos de Queries
#    Padrão de organização
    QuerySortItem:
      description: todo
      properties:
        key:
          type: string
          pattern: "^([a-zA-Z0-9_]){1,128}$"
          nullable: false
          minLength: 1
          maxLength: 128
        value:
          type: string
          enum: [ASC, DESC]
          nullable: false
          default: "ASC"
      required:
        - key
        - value

    QueryRequestSort:
      description: todo
      type: array
      items:
        $ref: "#/components/schemas/QuerySortItem"
      minItems: 0
      maxItems: 2147483647

    QueryRequestFilterItem:
      description: todo
      properties:
        key:
          type: string
          pattern: "^([a-zA-Z0-9_]){1,64}$"
          nullable: false
          minLength: 1
          maxLength: 64
        value:
          type: string
          pattern: '^[a-zA-Z0-9À-ÿ\s/\\_\,]{1,2048}$'
          nullable: false
          minLength: 1
          maxLength: 2048
        operator:
          type: string
          enum: [ EQ, GT, GTE, LT, LTE, IN, NOT_IN, IN_LIKE, NOT_IN_LIKE ]
          default: "EQ"
      required:
        - key
        - value

    QueryRequestPagination:
      description: todo
      properties:
        pageNumber:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
          default: 0
        pageSize:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
          default: 10
      required:
        - pageNumber
        - pageSize

#    Query Request
    QueryRequest:
      description: todo
      type: object
      properties:
        filter:
          type: array
          items:
            $ref: "#/components/schemas/QueryRequestFilterItem"
          minItems: 0
          maxItems: 2147483647
        pagination:
          $ref: "#/components/schemas/QueryRequestPagination"
        sort:
          $ref: "#/components/schemas/QueryRequestSort"

#    Query Response
    QueryResponsePagination:
      description: todo
      allOf:
        - $ref: "#/components/schemas/QueryRequestPagination"
        - type: object
          properties:
            totalCount:
              type: integer
              format: int64
              minimum: 0
              maximum: 9223372036854775807
              nullable: false
            resultSize:
              type: integer
              format: int32
              minimum: 0
              maximum: 2147483647
              nullable: false
          required:
            - totalCount
            - resultSize

    QueryResponse:
      description: todo
      type: object
      x-parent: abstract
      properties:
        pagination:
          $ref: "#/components/schemas/QueryResponsePagination"
      required:
        - pagination
